Flow Controller:
  name: send_tail_to_core
  comment: Tail /var/log/messages and send to remote process group
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors:
- name: TailFile
  class: org.apache.nifi.processors.standard.TailFile
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    File Location:
    File to Tail: /Users/scarroll/Documents/workspace/town_hall_presentation/minifi-0.0.1/logs/minifi-app.log
    Initial Start Position: Current Time
    Rolling Filename Pattern:
Connections:
- name: TailFile/success/d7cb3d84-0156-1000-0000-000000000000
  source name: TailFile
  source relationship name: success
  destination name: d7cb3d84-0156-1000-7839-27fe92617723
  max work queue size: 10000
  max work queue data size: 1 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
Remote Processing Groups:
- name: http://192.168.100.12:8080/nifi
  url: http://192.168.100.12:8080/nifi
  comment: ''
  timeout: 30 sec
  yield period: 10 sec
  Input Ports:
  #- id: d7cb3d84-0156-1000-0000-000000000000
  - id: d7cb3d84-0156-1000-7839-27fe92617723
    name: From The Edge
    comment: ''
    max concurrent tasks: 1
    use compression: false
